FROM python:3.8

RUN apt-get update
RUN pip install --upgrade pip

RUN pip install django
RUN pip install psycopg2
RUN pip install django-extensions
RUN pip install jupyterlab
RUN pip install django-crispy-forms
RUN pip install Pillow
RUN pip install mongoengine
